### ISSUE TITLE
Error when invoked with gpt-4

### ISSUE THREAD

**Issue by edshamis** [mountaineerbr/shellChatGPT#3]
❯ ~/repos/bin/shellChatGPT/chatgpt.sh -m gpt-4
Max Input/Resp: 1024 + 256 (1280) tkns
Prompt:
hi
Confirm prompt? [Y]es, [n]o, [e]dit, [r]edo or [a]bort ^M
######################################################################################################################################################################################## 100.0%
jq: error (at /home/ed/.cache/chatgptsh/chatgpt.json:8): Cannot iterate over null (null)
{
  "error": {
    "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}

**Comment by mountaineerbr** [comment]
I have not gotten access to gpt4 yet, so I tried to implement it based on some blogs... It **should** be working with the chat/completions endpoint, IDK why it is not... I will check that out tonight.

Thanks for reporting!

**Comment by mountaineerbr** [comment]
Ok i found the bug... I had written `gpt4-` instead of `gpt-4` in the case statement to select endpoints... Hopefully, it should be working now! Cheers!

**Comment by mountaineerbr** [comment]
commit bd82854

**Comment by mountaineerbr** [comment]
@edshamis I just got access to gpt-4! yay!
Do you know if that is possible to implement image modality with gpt-4 with the API endpoint?
I read some people mentioning that feature is only available through the API but I just checked the API Docs and there is no mention of it..
